---
- hosts: 127.0.0.1

  vars:
    static_containers:
    - { name: "ildh", image: "aharnum/ildh-docker", domain: "handbook.floeproject.local" }
    - { name: "fluidproject", image: "aharnum/fluidproject-docker" , domain: "fluidproject.local"}
  tasks:
      - name: create docker-compose file
        template:
          src: "templates/beachfront-compose.j2"
          dest: "./beachfront-compose.yml"
      - name: create nginx config files for each static site
        template:
          src: "templates/beachfront-nginx.j2"
          dest: "./{{ item.domain }}.conf"
        with_items: static_containers
      - name: create Dockerfile
        template:
            src: "templates/beachfront-Dockerfile.j2"
            dest: "./Dockerfile"
